languageCode: 'fr'
baseURL: ''
removePathAccents: true

params:
  contact:
    email:
      content: proust@arthaud.dev
      prefix: "mailto:"
  seo:
    author: Arthaud Proust
    title: Une sœur et un frère
    desc: "En 2012, notre père nous immortalise sur les quais de Bordeaux. 10 ans plus tard, il nous proposa de refaire les photos"
    subject: "photo"
    url: ''
    hero: /sprites/hero-min.png
    logo: /sprites/logo-min.png
    links:
      facebook: https://www.facebook.com/arthaudproust.fr
      instagram: https://www.instagram.com/arthaudproust
      linkedin: https://www.linkedin.com/in/arthaud-proust

taxonomies: